pipeline {
    agent any

    environment {
        VENV = 'venv'
        PYTHON_ENV = "${env.python}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Setup Python Environment') {
            steps {
                bat '"%PYTHON_HOME%\\python" -m venv venv'
                bat '"venv\\Scripts\\activate"'
                bat '"pip" install --upgrade pip'
                bat '"pip" install -r requirements.txt'
            }
        }
        stage('Code Linting') {
            steps {
                bat "pip install flask && pip install pylint"
            }
        }
    }
    post {
        success {
            echo 'Success. Linting Passed.'
        }
        failure {
            echo 'Error in linting'
        }
    }
}
