pipeline {
    agent any

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Setup virtual environment') {
            steps {
                sh 'python3 -m venv venv'
                sh '. venv/bin/activate'
            }
        }

        stage('Install dependencies') {
            steps {
                script {
                    sh "chmod -R 777 ${env.WORKSPACE}"
                    sh '. venv/bin/activate && pip install -r requirements.txt && pip install flask_cors && pip install jwt'
                }
            }
        }

        stage('Run unittests') {
            steps {
                script {
                    sh '''
                    export PYTHONPATH="$WORKSPACE/code-and-docs-x00174641:$PYTHONPATH"
                    . venv/bin/activate
                    pytest -W ignore::DeprecationWarning
                    '''
                }
            }
        }
        stage('Build WebApp') {
            steps {
                script {
                    sh '''
                    cd client
                    npm install
                    npm run build
                    '''
                }
            }
        }
    }
}
