pipeline {
    agent any

    environment {
        VENV = 'venv'
        PYTHON_ENV = "${env.PYTHON}"
        PIP_ENV = "${env.PIP}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Setup Python Environment') {
            steps {
                bat "\"${env.PYTHON_ENV}\" -m venv venv"
                bat '"venv\\Scripts\\activate"'
                bat "venv\\Scripts\\activate.bat && \"${env.PIP_ENV}\" install pylint"
                bat 'pylint --rcfile=./pylint.rc app/'
            }
        }
        stage('Code Linting') {
            steps {
                bat "cd"
                bat "dir"
                bat 'pylint --rcfile=./pylint.rc app/'
            }
        }
    }
    post {
        success {
            echo 'Success. Linting Passed.'
        }
        failure {
            echo 'Error in linting'
        }
    }
}
